package project_gomo_updating;

/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * gomo_forgotpassword.java
 *
 * Created on 26 Aug, 2013, 8:07:06 AM
 */

/**
 *
 * @author Nikhil
 */
import java.sql.DriverManager;
import com.mysql.jdbc.Connection;
import com.mysql.jdbc.Statement;
import java.sql.ResultSet;
import javax.swing.JOptionPane;
public class gomo_forgotpassword extends javax.swing.JFrame {

    /** Creates new form gomo_forgotpassword */
    public gomo_forgotpassword() {
        initComponents();
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        t2 = new javax.swing.JTextField();
        jButton1 = new javax.swing.JButton();
        jLabel5 = new javax.swing.JLabel();
        l1 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        t1 = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        jButton2 = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();
        l3 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        l2 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setLayout(null);

        jLabel2.setFont(new java.awt.Font("Tahoma", 0, 18));
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("Please enter the required details :");
        jPanel1.add(jLabel2);
        jLabel2.setBounds(20, 70, 270, 30);

        t2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                t2ActionPerformed(evt);
            }
        });
        jPanel1.add(t2);
        t2.setBounds(190, 180, 180, 20);

        jButton1.setText("Generate Password");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton1);
        jButton1.setBounds(140, 240, 230, 23);

        jLabel5.setFont(new java.awt.Font("Tahoma", 0, 14));
        jLabel5.setForeground(new java.awt.Color(255, 255, 255));
        jLabel5.setText("SECRET QUESTION:");
        jPanel1.add(jLabel5);
        jLabel5.setBounds(20, 140, 130, 30);

        l1.setFont(new java.awt.Font("Tahoma", 0, 14));
        jPanel1.add(l1);
        l1.setBounds(190, 140, 360, 30);

        jLabel6.setFont(new java.awt.Font("Tahoma", 0, 14));
        jLabel6.setForeground(new java.awt.Color(255, 255, 255));
        jLabel6.setText("ANSWER:");
        jPanel1.add(jLabel6);
        jLabel6.setBounds(20, 180, 70, 20);

        t1.setToolTipText("After entering the username , click on the space provided for the answer");
        t1.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                t1FocusLost(evt);
            }
        });
        jPanel1.add(t1);
        t1.setBounds(190, 110, 180, 20);

        jLabel4.setFont(new java.awt.Font("Tahoma", 0, 14));
        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setText("USERNAME :");
        jPanel1.add(jLabel4);
        jLabel4.setBounds(20, 110, 150, 20);

        jButton2.setText("LOGIN");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton2);
        jButton2.setBounds(170, 280, 160, 23);

        jLabel3.setFont(new java.awt.Font("Times New Roman", 1, 24));
        jLabel3.setText("FORGOT PASSWORD ??");
        jPanel1.add(jLabel3);
        jLabel3.setBounds(510, 20, 273, 28);

        l3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/project_gomo_updating/images (2).jpg"))); // NOI18N
        jPanel1.add(l3);
        l3.setBounds(130, 330, 260, 194);

        jLabel7.setIcon(new javax.swing.ImageIcon(getClass().getResource("/project_gomo_updating/indian-railway.jpg"))); // NOI18N
        jPanel1.add(jLabel7);
        jLabel7.setBounds(590, 60, 690, 440);

        l2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/project_gomo_updating/images.jpg"))); // NOI18N
        jPanel1.add(l2);
        l2.setBounds(360, 450, 280, 180);

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/project_gomo_updating/Backgrounds-modern-wallpapers-hd-modern-wallpaper-16.jpg"))); // NOI18N
        jLabel1.setMinimumSize(new java.awt.Dimension(1365, 710));
        jPanel1.add(jLabel1);
        jLabel1.setBounds(0, 0, 1360, 700);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 1360, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 701, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void t2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_t2ActionPerformed
        // TODO add your handling code here:
}//GEN-LAST:event_t2ActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        String Username=t1.getText();
        try {
            Class.forName("java.sql.DriverManager");
            Connection con = (Connection)DriverManager.getConnection("jdbc:mysql://localhost:3306/gomo","root","DPS");
            Statement s = (Statement) con.createStatement();
            String query ="SELECT Secret_Answer FROM signups where Username = '"+Username+"';";
            ResultSet r = s.executeQuery(query);
            if(r.next()) {
                String Ans = r.getString(1);
                String U_Ans = t2.getText();
                if(U_Ans.equals(Ans)) {
                    Statement stmt = (Statement) con.createStatement();
                    String query1="SELECT Name,Password FROM signups where Username = '"+Username+"';";
                    ResultSet rs= stmt.executeQuery(query1);
                    if(rs.next()) {
                        String Name = rs.getString(1);
                        String Password = rs.getString(2);
                        int More=JOptionPane.showConfirmDialog(this,"Are you "+Name+"?","Confirm",JOptionPane.YES_NO_OPTION);
                        if(More==0) {
                            JOptionPane.showMessageDialog(this,"The Password is : "+Password);} else {
                            JOptionPane.showMessageDialog(this,"Please Check your details");
                            }
                    }
                } else {
                    JOptionPane.showMessageDialog(this,"The answer entered while signing up doesn't match the given answer. Hence the password cannot be generated");
                }
            } else {
                JOptionPane.showMessageDialog(this,"There is no user in our records having username "+Username+". Please recheck your details");
            }
        } catch(Exception e) {
            JOptionPane.showMessageDialog(this, e.getMessage());
        }
}//GEN-LAST:event_jButton1ActionPerformed

    private void t1FocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_t1FocusLost
        // TODO add your handling code here:
        String Username=t1.getText();
        try {
            Class.forName("java.sql.DriverManager");
            Connection con = (Connection)DriverManager.getConnection("jdbc:mysql://localhost:3306/gomo","root","DPS");
            Statement s = (Statement) con.createStatement();
            String query="SELECT Secret_Question FROM signups where Username = '"+Username+"';";
            ResultSet r= s.executeQuery(query);
            if(r.next()) {
                String ques = r.getString(1);
                l1.setText(ques);
            } else {
                JOptionPane.showMessageDialog(this,"There is no user in our records having username "+Username+". Please recheck your details");
                t1.setText("");
            }
        } catch (Exception e) {
            JOptionPane.showMessageDialog(this, e.getMessage());
        }
}//GEN-LAST:event_t1FocusLost

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        gomo_openingpage a = new gomo_openingpage();
        a.setVisible(true);
        this.dispose();
}//GEN-LAST:event_jButton2ActionPerformed

    /**
    * @param args the command line arguments
    */
    public static void main(String args[]) {
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new gomo_forgotpassword().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JLabel l1;
    private javax.swing.JLabel l2;
    private javax.swing.JLabel l3;
    private javax.swing.JTextField t1;
    private javax.swing.JTextField t2;
    // End of variables declaration//GEN-END:variables

}
