package project_gomo_updating;

/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * gomo_signup.java
 *
 * Created on 26 Aug, 2013, 8:10:22 AM
 */
/**
 *
 * @author Nikhil
 */
import project_gomo_updating.gomo_openingpage;
import java.sql.DriverManager;
import com.mysql.jdbc.Connection;
import com.mysql.jdbc.Statement;
import java.sql.ResultSet;
import javax.swing.JOptionPane;

public class gomo_signup extends javax.swing.JFrame {

    public gomo_signup() {
        initComponents();

    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        jLabel12 = new javax.swing.JLabel();
        t6 = new javax.swing.JTextField();
        jButton3 = new javax.swing.JButton();
        t4 = new javax.swing.JPasswordField();
        jLabel13 = new javax.swing.JLabel();
        r1 = new javax.swing.JRadioButton();
        jLabel14 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        t2 = new javax.swing.JTextField();
        t3 = new javax.swing.JTextField();
        jLabel16 = new javax.swing.JLabel();
        r2 = new javax.swing.JRadioButton();
        jButton4 = new javax.swing.JButton();
        jLabel17 = new javax.swing.JLabel();
        t5 = new javax.swing.JPasswordField();
        c1 = new javax.swing.JComboBox();
        jLabel18 = new javax.swing.JLabel();
        cm = new javax.swing.JComboBox();
        jLabel19 = new javax.swing.JLabel();
        t1 = new javax.swing.JTextField();
        cd = new javax.swing.JComboBox();
        jLabel20 = new javax.swing.JLabel();
        jLabel21 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setMinimumSize(new java.awt.Dimension(1365, 710));
        getContentPane().setLayout(null);

        jPanel1.setLayout(null);

        jPanel2.setLayout(null);

        jLabel12.setText("SECRET ANSWER");
        jPanel2.add(jLabel12);
        jLabel12.setBounds(10, 303, 170, 14);

        t6.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                t6FocusGained(evt);
            }
        });
        jPanel2.add(t6);
        t6.setBounds(134, 300, 138, 20);

        jButton3.setText("SIGN UP");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });
        jPanel2.add(jButton3);
        jButton3.setBounds(10, 326, 390, 23);
        jPanel2.add(t4);
        t4.setBounds(140, 200, 140, 20);

        jLabel13.setText("GENDER");
        jPanel2.add(jLabel13);
        jLabel13.setBounds(10, 139, 100, 14);

        r1.setText("M");
        jPanel2.add(r1);
        r1.setBounds(114, 139, 41, 23);

        jLabel14.setText("DOB");
        jPanel2.add(jLabel14);
        jLabel14.setBounds(10, 116, 90, 14);

        jLabel15.setText("PASSWORD");
        jPanel2.add(jLabel15);
        jLabel15.setBounds(10, 203, 120, 14);

        t2.setText("Year");
        t2.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                t2FocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                t2FocusLost(evt);
            }
        });
        jPanel2.add(t2);
        t2.setBounds(290, 110, 59, 20);

        t3.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                t3FocusLost(evt);
            }
        });
        jPanel2.add(t3);
        t3.setBounds(140, 170, 139, 20);

        jLabel16.setText("USERNAME");
        jPanel2.add(jLabel16);
        jLabel16.setBounds(10, 169, 110, 14);

        r2.setText("F");
        jPanel2.add(r2);
        r2.setBounds(167, 139, 31, 23);

        jButton4.setText("<html><u><b>Check Availability</b></u></html>");
        jButton4.setBorder(null);
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });
        jPanel2.add(jButton4);
        jButton4.setBounds(290, 170, 101, 15);

        jLabel17.setText("WELCOME to NSRS ! Thank you for choosing our services !! For Signing up give the required details ...");
        jPanel2.add(jLabel17);
        jLabel17.setBounds(10, 60, 491, 14);
        jPanel2.add(t5);
        t5.setBounds(140, 240, 140, 20);

        c1.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Please select a question", "What is your pets name ?", "What was the name of your first school ?", "What is your father’s middle name ?", "Which car/bike was your first vehicle ?", "What is the name of your place of birth ?" }));
        c1.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                c1FocusLost(evt);
            }
        });
        jPanel2.add(c1);
        c1.setBounds(134, 269, 233, 20);

        jLabel18.setFont(new java.awt.Font("Tahoma", 0, 18));
        jLabel18.setText("SIGN UP ");
        jPanel2.add(jLabel18);
        jLabel18.setBounds(190, 30, 75, 22);

        cm.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "month", "Jan", "Feb", "Mar", "Apr", "May", "Jun", "Jul", "Aug", "Sep", "Oct", "Nov ", "Dec" }));
        cm.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                cmFocusLost(evt);
            }
        });
        jPanel2.add(cm);
        cm.setBounds(195, 110, 90, 20);

        jLabel19.setText("SECRET QUESTION");
        jPanel2.add(jLabel19);
        jLabel19.setBounds(10, 272, 160, 14);
        jPanel2.add(t1);
        t1.setBounds(114, 86, 173, 20);

        cd.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "date", "1", "2", "3", "4", "5", "6", "7", "8", "9", "10", "11", "12", "13", "14", "15", "16", "17", "18", "19", "20", "21", "22", "23", "24", "25", "26", "27", "28", "29", "30", "31" }));
        jPanel2.add(cd);
        cd.setBounds(120, 110, 70, 20);

        jLabel20.setText("RE-ENTER PASSWORD");
        jPanel2.add(jLabel20);
        jLabel20.setBounds(10, 244, 180, 14);

        jLabel21.setText("NAME");
        jPanel2.add(jLabel21);
        jLabel21.setBounds(10, 85, 100, 22);

        jPanel1.add(jPanel2);
        jPanel2.setBounds(20, 110, 510, 430);

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/project_gomo_updating/Indian-Luxury-Train-Golden-Chariot-Journey.jpg"))); // NOI18N
        jPanel1.add(jLabel2);
        jLabel2.setBounds(540, 20, 810, 640);

        jLabel3.setFont(new java.awt.Font("Tahoma", 0, 14));
        jLabel3.setText("OUR FIRST CLASS SERVICE TO THE CUSTOMERS...");
        jPanel1.add(jLabel3);
        jLabel3.setBounds(190, 650, 340, 14);

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/project_gomo_updating/fnpfnf.png"))); // NOI18N
        jPanel1.add(jLabel1);
        jLabel1.setBounds(0, 0, 1360, 720);

        getContentPane().add(jPanel1);
        jPanel1.setBounds(0, 0, 1360, 710);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void t6FocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_t6FocusGained
        // TODO add your handling code here:
        if(c1.getSelectedIndex()==0) {
            JOptionPane.showMessageDialog(null,"Please Select a question. Since you haven't selected any question. A default question has been Selected.");
            c1.setSelectedIndex(1);
        }
}//GEN-LAST:event_t6FocusGained

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        // TODO add your handling code here:
        String Name,dob = "",Gender = "",Username,Password,R_Password,C_Password = "",SecretQuestion,SecretAnswer,date,month;
        Name=t1.getText();
        int year=Integer.parseInt(t2.getText());
        int a=cd.getSelectedIndex();
        int b=cm.getSelectedIndex();

        if(!((b==31&&(a==2||a==4||a==6||a==9||a==11))||(a==2&&(b==30))||((year%4!=0)&&(a==2&&b==29)))) {
            if(a/10==0) {
                dob = year+"-0"+a+"-"+b;
            } else {
                dob = year+"-"+a+"-"+b;
            }
        }
        {
            if (r1.isSelected()) {
                Gender="M";} else if(r2.isSelected()) {
                    Gender="F";}
        }
        Username=t3.getText();
        Password=new String(t4.getPassword());
        R_Password=new String(t5.getPassword());
        {
            if (Password .equals(R_Password)) {
                C_Password=Password;
            } else {
                t4.setText("");
                t5.setText("");
                JOptionPane.showMessageDialog(this,"The Password and the Password Re-Entered are not the same");
            }
        }
        SecretQuestion=(String)c1.getSelectedItem();
        if(c1.getSelectedIndex()==0) {
            JOptionPane.showMessageDialog(null,"Please Select a question. Since you haven't selected any question. A default question has been Selected.");
            c1.setSelectedIndex(1);
        }
        SecretAnswer=t6.getText();
        try {
            Class.forName("java.sql.DriverManager");
            Connection con = (Connection)DriverManager.getConnection("jdbc:mysql://localhost:3306/gomo","root","DPS");
            Statement stmt = (Statement) con.createStatement();
            String query="INSERT INTO signups VALUES('"+Name+"','"+dob+"','"+Gender+"','"+Username+"','"+C_Password+"','"+SecretQuestion+"','"+SecretAnswer+"');";
            stmt.executeUpdate(query);

        } catch(Exception e) {
            JOptionPane.showMessageDialog(this, e.getMessage());
        }
        gomo_openingpage c = new gomo_openingpage();
        c.setVisible(true);
        this.dispose();
        JOptionPane.showMessageDialog(null,"You account is now created !!");
    }//GEN-LAST:event_jButton3ActionPerformed

    private void t2FocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_t2FocusGained
        // TODO add your handling code here:
        t2.setText("");
}//GEN-LAST:event_t2FocusGained

    private void t2FocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_t2FocusLost
        // TODO add your handling code here:
        int year=Integer.parseInt(t2.getText());
        if(year<1913||year>2013) {
            JOptionPane.showMessageDialog(null,"Please Enter a valid year");
        }
}//GEN-LAST:event_t2FocusLost

    private void t3FocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_t3FocusLost
        // TODO add your handling code here:
        String c_username = t3.getText();
        try {
            Class.forName("java.sql.DriverManager");
            Connection con = (Connection)DriverManager.getConnection("jdbc:mysql://localhost:3306/gomo","root","DPS");
            Statement stmt = (Statement) con.createStatement();
            String query1="SELECT Username FROM signups where Username = '"+c_username+"';";
            ResultSet rs= stmt.executeQuery(query1);
            if(rs.next()) {
                JOptionPane.showMessageDialog(null,"This username already exist. Please check for any other username");
                t3.setText("");t4.setText("");t5.setText("");
            }
        } catch(Exception e) {
            JOptionPane.showMessageDialog(this, e.getMessage());
        }
    }//GEN-LAST:event_t3FocusLost

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
        // TODO add your handling code here:
        String c_username = t3.getText();
        try {
            Class.forName("java.sql.DriverManager");
            Connection con = (Connection)DriverManager.getConnection("jdbc:mysql://localhost:3306/gomo","root","DPS");
            Statement stmt = (Statement) con.createStatement();
            String query1="SELECT Username FROM signups where Username = '"+c_username+"';";
            ResultSet rs= stmt.executeQuery(query1);
            if(rs.next()) {
                JOptionPane.showMessageDialog(null,"This username already exist. Please check for any other username");
                t3.setText("");t4.setText("");t5.setText("");
            } else {
                JOptionPane.showMessageDialog(null,"Valid Username");
            }
        } catch(Exception e) {
            JOptionPane.showMessageDialog(this, e.getMessage());
        }
}//GEN-LAST:event_jButton4ActionPerformed

    private void c1FocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_c1FocusLost
        // TODO add your handling code here:
}//GEN-LAST:event_c1FocusLost

    private void cmFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_cmFocusLost
        // TODO add your handling code here:
        int a=cd.getSelectedIndex();
        int b=cd.getSelectedIndex();
        int year=Integer.parseInt(t2.getText());
        if ((b==31&&(a==2||a==4||a==6||a==9||a==11))||(a==2&&(b==30))||((year%4!=0)&&(a==2&&b==29))) {
            JOptionPane.showMessageDialog(null,"Entered an invalid date.Please Enter a valid one.");
            cd.setSelectedIndex(0);
            cm.setSelectedIndex(0);
        }
}//GEN-LAST:event_cmFocusLost

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        java.awt.EventQueue.invokeLater(new Runnable() {

            public void run() {
                new gomo_signup().setVisible(true);
            }
        });
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JComboBox c1;
    private javax.swing.JComboBox cd;
    private javax.swing.JComboBox cm;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JRadioButton r1;
    private javax.swing.JRadioButton r2;
    private javax.swing.JTextField t1;
    private javax.swing.JTextField t2;
    private javax.swing.JTextField t3;
    private javax.swing.JPasswordField t4;
    private javax.swing.JPasswordField t5;
    private javax.swing.JTextField t6;
    // End of variables declaration//GEN-END:variables
}
