/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * gomo_feedback.java
 *
 * Created on 13 Nov, 2013, 10:01:13 PM
 */

package project_gomo_updating;

/**
 *
 * @author Nikhil
 */
import project_gomo_updating.project_gomo_2;
import com.mysql.jdbc.Statement;
import com.mysql.jdbc.Connection;
import java.sql.DriverManager;
import java.sql.ResultSet;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
public class gomo_feedback extends javax.swing.JFrame {

    /** Creates new form gomo_feedback */
    public gomo_feedback() {
        initComponents();
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTextArea1 = new javax.swing.JTextArea();
        jScrollPane2 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jLabel3 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        jLabel4 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setMinimumSize(new java.awt.Dimension(1365, 701));
        getContentPane().setLayout(null);

        jPanel1.setLayout(null);

        jLabel2.setFont(new java.awt.Font("Tahoma", 0, 14));
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("GIVE YOUR FEEDBACK :");
        jPanel1.add(jLabel2);
        jLabel2.setBounds(40, 30, 160, 17);

        jTextArea1.setColumns(20);
        jTextArea1.setRows(5);
        jTextArea1.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                jTextArea1FocusGained(evt);
            }
        });
        jTextArea1.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                jTextArea1KeyTyped(evt);
            }
        });
        jScrollPane1.setViewportView(jTextArea1);

        jPanel1.add(jScrollPane1);
        jScrollPane1.setBounds(210, 20, 1040, 50);

        jTable1.setFont(new java.awt.Font("Tahoma", 0, 18));
        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Other FEEDBACKS"
            }
        ));
        jScrollPane2.setViewportView(jTable1);

        jPanel1.add(jScrollPane2);
        jScrollPane2.setBounds(40, 110, 1200, 290);

        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("(maximum 150 characters)");
        jPanel1.add(jLabel3);
        jLabel3.setBounds(40, 60, 170, 14);

        jButton1.setText("SEND FEEDBACK");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton1);
        jButton1.setBounds(580, 80, 200, 23);

        jButton2.setText("SIGN OUT");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton2);
        jButton2.setBounds(40, 400, 90, 23);

        jButton3.setText("EXIT");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton3);
        jButton3.setBounds(130, 400, 100, 23);

        jLabel4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/project_gomo_updating/AHIL.jpg"))); // NOI18N
        jPanel1.add(jLabel4);
        jLabel4.setBounds(340, 410, 590, 260);

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/project_gomo_updating/Backgrounds-modern-wallpapers-hd-modern-wallpaper-04.jpg"))); // NOI18N
        jPanel1.add(jLabel1);
        jLabel1.setBounds(0, 0, 1360, 690);

        getContentPane().add(jPanel1);
        jPanel1.setBounds(0, 0, 1360, 700);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        String feedback = jTextArea1.getText();
        try {
                    Class.forName("java.sql.DriverManager");
                    Connection con = (Connection) DriverManager.getConnection("jdbc:mysql://localhost:3306/gomo","root","DPS");
                    Statement stmt1 = (Statement) con.createStatement();
                    String query1 = "INSERT INTO feedbacks VALUES('" + feedback + "');";
                    stmt1.executeUpdate(query1);

                } catch (Exception e) {
                    JOptionPane.showMessageDialog(this, e.getMessage());
                }
        JOptionPane.showMessageDialog(null,"Thank you for your feedback !!! ");
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jTextArea1KeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTextArea1KeyTyped
        // TODO add your handling code here:
        String x = jTextArea1.getText();
        int l = x.length();
        if(l>=150) {
            x = x.substring(0,149);
            jTextArea1.setText(x);
        }
    }//GEN-LAST:event_jTextArea1KeyTyped

    private void jTextArea1FocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_jTextArea1FocusGained
        // TODO add your handling code here:
        DefaultTableModel model = (DefaultTableModel) jTable1.getModel();
        try {
            Class.forName("java.sql.DriverManager");
            Connection con = (Connection)DriverManager.getConnection("jdbc:mysql://localhost:3306/gomo","root","DPS");
            Statement s = (Statement) con.createStatement();
            Statement s1 = (Statement) con.createStatement();
            String query="SELECT * FROM FEEDBACKS;";
            String q = "SELECT count(feedback) from Feedbacks";
            ResultSet r= s.executeQuery(query);
            ResultSet r1= s1.executeQuery(q);
            if(r1.next())
            {   while (r.next()) {
                String feedback = r.getString(1);
                model.addRow(new Object[]{feedback});
            }}
            else
            {
                String feedback = "NO FEEDBACKS YET !!! WE ARE LUCKY HERE TO GET THE FIRST FEEDBACK FROM YOU !!!";
                model.addRow(new Object[]{feedback});
            }}
         catch(Exception e) {
            JOptionPane.showMessageDialog(this, e.getMessage());
        }
    }//GEN-LAST:event_jTextArea1FocusGained

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:
        gomo_openingpage a= new gomo_openingpage();
        a.setVisible(true);
        this.dispose();
        JOptionPane.showMessageDialog(null,"You are successfully logged out !!");
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        // TODO add your handling code here:
        JOptionPane.showMessageDialog(null,"Thank you !! Please visit Again !!");
        System.exit(0);
    }//GEN-LAST:event_jButton3ActionPerformed

    /**
    * @param args the command line arguments
    */
    public static void main(String args[]) {
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new gomo_feedback().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTable jTable1;
    private javax.swing.JTextArea jTextArea1;
    // End of variables declaration//GEN-END:variables

}
