/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * gomo_kno_us.java
 *
 * Created on 13 Nov, 2013, 10:31:54 PM
 */

package project_gomo_updating;

/**
 *
 * @author Nikhil
 */
public class gomo_kno_us extends javax.swing.JFrame {

    /** Creates new form gomo_kno_us */
    public gomo_kno_us() {
        initComponents();
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(null);

        jPanel1.setMinimumSize(new java.awt.Dimension(1365, 701));
        jPanel1.setLayout(null);

        jLabel2.setFont(new java.awt.Font("Monotype Corsiva", 0, 18));
        jLabel2.setText("National Shuttle Reservation Service  is a premium service . The service is designed to give you great comfort");
        jPanel1.add(jLabel2);
        jLabel2.setBounds(340, 100, 700, 20);

        jLabel3.setFont(new java.awt.Font("Monotype Corsiva", 0, 18));
        jLabel3.setText("with cosy coaches at an afforrdable price. The service is faster with limited stops ensuring that the travel time is low.");
        jPanel1.add(jLabel3);
        jLabel3.setBounds(320, 130, 760, 20);

        jLabel4.setFont(new java.awt.Font("Monotype Corsiva", 0, 18));
        jLabel4.setText("The service cover the top six attractions in india. ");
        jPanel1.add(jLabel4);
        jLabel4.setBounds(550, 160, 313, 20);

        jLabel5.setFont(new java.awt.Font("Monotype Corsiva", 0, 18));
        jLabel5.setText("These include , Delhi , Mumbai , Bangalore , Chennai ,  Hyderabad  and Kolkata. ");
        jPanel1.add(jLabel5);
        jLabel5.setBounds(460, 190, 530, 20);

        jLabel6.setFont(new java.awt.Font("Monotype Corsiva", 0, 18));
        jLabel6.setText("  The comfort and the fun you would have throughout the journey is totally worth the prices of the ticket.");
        jPanel1.add(jLabel6);
        jLabel6.setBounds(350, 230, 690, 20);

        jLabel7.setIcon(new javax.swing.ImageIcon(getClass().getResource("/project_gomo_updating/nsrs network.png"))); // NOI18N
        jLabel7.setText("jLabel7");
        jPanel1.add(jLabel7);
        jLabel7.setBounds(360, 260, 700, 390);

        jButton1.setText("BACK TO HOME PAGE");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton1);
        jButton1.setBounds(1173, 490, 170, 23);

        jButton2.setText("NEXT");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton2);
        jButton2.setBounds(1170, 520, 150, 23);

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/project_gomo_updating/bck3.png"))); // NOI18N
        jPanel1.add(jLabel1);
        jLabel1.setBounds(0, 0, 1360, 700);

        getContentPane().add(jPanel1);
        jPanel1.setBounds(0, 0, 1365, 701);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        gomo_openingpage a = new gomo_openingpage();
        a.setVisible(true);
        this.dispose();
}//GEN-LAST:event_jButton1ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:
        gomo_kno_us_2 b = new gomo_kno_us_2();
        b.setVisible(true);
        this.dispose();
}//GEN-LAST:event_jButton2ActionPerformed

    /**
    * @param args the command line arguments
    */
    public static void main(String args[]) {
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new gomo_kno_us().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JPanel jPanel1;
    // End of variables declaration//GEN-END:variables

}
