package project_gomo_updating;

/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * gomo_openingpage.java
 *
 * Created on 26 Aug, 2013, 7:42:41 AM
 */


/**
 *
 * @author Nikhil
 */
import java.sql.DriverManager;
import com.mysql.jdbc.Connection;
import com.mysql.jdbc.Statement;
import java.sql.ResultSet;
import javax.swing.JOptionPane;
public class gomo_openingpage extends javax.swing.JFrame {

    String abcd = "1";
    /** Creates new form gomo_openingpage */
    public gomo_openingpage() {

        initComponents();
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel9 = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        t1 = new javax.swing.JTextField();
        p1 = new javax.swing.JPasswordField();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jLabel7 = new javax.swing.JLabel();
        jButton3 = new javax.swing.JButton();
        l1 = new javax.swing.JLabel();
        lm = new javax.swing.JLabel();
        jButton4 = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();

        jLabel9.setText("jLabel9");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setMinimumSize(new java.awt.Dimension(1365, 710));

        jPanel1.setLayout(null);

        jLabel1.setFont(new java.awt.Font("Times New Roman", 1, 24));
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("WELCOME TO NSRS !!");
        jPanel1.add(jLabel1);
        jLabel1.setBounds(540, 80, 256, 28);

        jPanel2.setBackground(new java.awt.Color(255, 255, 255));
        jPanel2.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jPanel2.setLayout(null);

        jLabel4.setFont(new java.awt.Font("Tahoma", 0, 14));
        jLabel4.setText("SIGN IN :");
        jPanel2.add(jLabel4);
        jLabel4.setBounds(30, 40, 60, 17);

        jLabel5.setText("PASSWORD : ");
        jPanel2.add(jLabel5);
        jLabel5.setBounds(30, 100, 110, 14);

        jLabel6.setText("USERNAME : ");
        jPanel2.add(jLabel6);
        jLabel6.setBounds(30, 70, 80, 14);
        jPanel2.add(t1);
        t1.setBounds(120, 70, 160, 20);
        jPanel2.add(p1);
        p1.setBounds(120, 100, 160, 20);

        jButton1.setText("LOGIN");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        jPanel2.add(jButton1);
        jButton1.setBounds(30, 130, 270, 23);

        jButton2.setBackground(new java.awt.Color(255, 255, 255));
        jButton2.setForeground(new java.awt.Color(0, 0, 102));
        jButton2.setText("<html><b><u>FORGOT PASSWORD ?? (Click here)</u></b></html>");
        jButton2.setBorder(null);
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        jPanel2.add(jButton2);
        jButton2.setBounds(30, 160, 270, 15);

        jLabel7.setText("NEW USER ? SIGN UP IMMEDIATELY !");
        jPanel2.add(jLabel7);
        jLabel7.setBounds(30, 190, 270, 14);

        jButton3.setText("SIGN UP");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });
        jPanel2.add(jButton3);
        jButton3.setBounds(30, 210, 270, 23);

        l1.setForeground(new java.awt.Color(255, 0, 0));
        jPanel2.add(l1);
        l1.setBounds(30, 110, 160, 0);

        lm.setForeground(new java.awt.Color(255, 0, 0));
        lm.setText(" ");
        jPanel2.add(lm);
        lm.setBounds(30, 10, 280, 20);

        jButton4.setBackground(new java.awt.Color(255, 255, 255));
        jButton4.setForeground(new java.awt.Color(0, 0, 102));
        jButton4.setText("<html><b><u>KNOW ABOUT US !!! (Click here)</u></b></html>");
        jButton4.setBorder(null);
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });
        jPanel2.add(jButton4);
        jButton4.setBounds(30, 240, 270, 15);

        jPanel1.add(jPanel2);
        jPanel2.setBounds(950, 220, 330, 267);

        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/project_gomo_updating/AHIL.jpg"))); // NOI18N
        jPanel1.add(jLabel3);
        jLabel3.setBounds(140, 220, 590, 260);

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/project_gomo_updating/Backgrounds-modern-wallpapers-hd-modern-wallpaper-04.jpg"))); // NOI18N
        jLabel2.setMinimumSize(new java.awt.Dimension(1365, 710));
        jPanel1.add(jLabel2);
        jLabel2.setBounds(0, 0, 1360, 710);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 1365, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 710, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        String Username=t1.getText();
        String Password=new String(p1.getPassword());
        if(Username.equals("")||Password.equals("") ) {
            lm.setText("Enter the details completely");
        } else {
            try {
                Class.forName("java.sql.DriverManager");
                Connection con = (Connection)DriverManager.getConnection("jdbc:mysql://localhost:3306/gomo","root","DPS");
                Statement s = (Statement) con.createStatement();
                String query="SELECT Password,Username FROM signups where Username = '"+Username+"';";
                ResultSet r= s.executeQuery(query);
                if(r.next()) {
                    String U_P = r.getString(1);
                    String U_U = r.getString(2);
                    if(U_P.equals(Password)&& U_U.equals(Username)) {
                        l1.setText("");
                        project_gomo_updating.Main.username = t1.getText();
                        new project_gomo_2(abcd).setVisible(true);
                        this.dispose();

                    } else
                        lm.setText("Wrong Username or Password . Check your details.");
                } else {
                    lm.setText("Wrong Username or Password . Check your details.");
                }
            } catch(Exception e) {
                JOptionPane.showMessageDialog(this, e.getMessage());
            }}
}//GEN-LAST:event_jButton1ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:
        gomo_forgotpassword b = new gomo_forgotpassword();
        b.setVisible(true);
        this.dispose();
}//GEN-LAST:event_jButton2ActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        // TODO add your handling code here:
        gomo_signup a = new gomo_signup();
        a.setVisible(true);
        this.dispose();
}//GEN-LAST:event_jButton3ActionPerformed

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
        // TODO add your handling code here:
        gomo_kno_us x = new gomo_kno_us();
        x.setVisible(true);
        this.dispose();

    }//GEN-LAST:event_jButton4ActionPerformed

    /*
     @param args the command line arguments
    */
    public static void main(String args[]) {
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new gomo_openingpage().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JLabel l1;
    private javax.swing.JLabel lm;
    private javax.swing.JPasswordField p1;
    private javax.swing.JTextField t1;
    // End of variables declaration//GEN-END:variables

}
