/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * NSRS_RAILWAY_NETWORK.java
 *
 * Created on 13 Nov, 2013, 5:24:32 PM
 */

package project_gomo_updating;

/**
 *
 * @author Nikhil
 */
public class NSRS_RAILWAY_NETWORK extends javax.swing.JFrame {

    /** Creates new form NSRS_RAILWAY_NETWORK */
    public NSRS_RAILWAY_NETWORK() {
        initComponents();
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(null);

        jPanel1.setLayout(null);

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/project_gomo_updating/india-railway.jpg"))); // NOI18N
        jPanel1.add(jLabel2);
        jLabel2.setBounds(410, 10, 640, 690);

        jButton1.setText("GO TO HOME PAGE");
        jPanel1.add(jButton1);
        jButton1.setBounds(1100, 440, 140, 23);

        jButton2.setText("GO BACK");
        jPanel1.add(jButton2);
        jButton2.setBounds(1100, 470, 140, 23);

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/project_gomo_updating/bck4.png"))); // NOI18N
        jLabel1.setText("jLabel1");
        jPanel1.add(jLabel1);
        jLabel1.setBounds(0, 0, 1360, 710);

        getContentPane().add(jPanel1);
        jPanel1.setBounds(0, 0, 1360, 710);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
    * @param args the command line arguments
    */
    public static void main(String args[]) {
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new NSRS_RAILWAY_NETWORK().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JPanel jPanel1;
    // End of variables declaration//GEN-END:variables

}
