package project_gomo_updating;


import javax.swing.table.DefaultTableModel;

/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * project_gomo_6.java
 *
 * Created on Oct 10, 2013, 1:19:29 PM
 */

/**
 *
 * @author Student
 */
import project_gomo_updating.gomo_forgotpassword;
import java.sql.DriverManager;
import com.mysql.jdbc.Connection;
import com.mysql.jdbc.Statement;
import java.sql.ResultSet;
import javax.swing.JOptionPane;

public class project_gomo_6 extends javax.swing.JFrame {


    /** Creates new form project_gomo_6 */
    public project_gomo_6() {
        initComponents();
        p1.setVisible(false);p2.setVisible(false);p3.setVisible(false);p4.setVisible(false);p5.setVisible(false);
    m1.setVisible(false);m2.setVisible(false);m3.setVisible(false);m4.setVisible(false);m5.setVisible(false);
    a1.setVisible(false);a2.setVisible(false);a3.setVisible(false);a4.setVisible(false);a5.setVisible(false);
    g1.setVisible(false);g2.setVisible(false);g3.setVisible(false);g4.setVisible(false);g5.setVisible(false);


    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        m3 = new javax.swing.JTextField();
        a3 = new javax.swing.JTextField();
        m4 = new javax.swing.JTextField();
        a4 = new javax.swing.JTextField();
        g2 = new javax.swing.JComboBox();
        p2 = new javax.swing.JLabel();
        Fare1 = new javax.swing.JTextField();
        p4 = new javax.swing.JLabel();
        g3 = new javax.swing.JComboBox();
        p3 = new javax.swing.JLabel();
        jLabel22 = new javax.swing.JLabel();
        jLabel19 = new javax.swing.JLabel();
        jLabel27 = new javax.swing.JLabel();
        jLabel21 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        jLabel20 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel23 = new javax.swing.JLabel();
        jLabel28 = new javax.swing.JLabel();
        jLabel24 = new javax.swing.JLabel();
        jLabel33 = new javax.swing.JLabel();
        g4 = new javax.swing.JComboBox();
        a5 = new javax.swing.JTextField();
        m5 = new javax.swing.JTextField();
        jLabel30 = new javax.swing.JLabel();
        p5 = new javax.swing.JLabel();
        jLabel31 = new javax.swing.JLabel();
        g5 = new javax.swing.JComboBox();
        jCheckBox1 = new javax.swing.JCheckBox();
        jLabel32 = new javax.swing.JLabel();
        jLabel17 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jLabel29 = new javax.swing.JLabel();
        a1 = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        m1 = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        p1 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        jLabel18 = new javax.swing.JLabel();
        jButton2 = new javax.swing.JButton();
        jLabel16 = new javax.swing.JLabel();
        jLabel25 = new javax.swing.JLabel();
        jLabel26 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        c1 = new javax.swing.JComboBox();
        m2 = new javax.swing.JTextField();
        jLabel11 = new javax.swing.JLabel();
        jLabel34 = new javax.swing.JLabel();
        a2 = new javax.swing.JTextField();
        g1 = new javax.swing.JComboBox();
        jLabel35 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setMinimumSize(new java.awt.Dimension(1365, 710));

        jPanel1.setLayout(null);

        jPanel2.setBackground(new java.awt.Color(204, 0, 0));
        jPanel2.setLayout(null);
        jPanel2.add(m3);
        m3.setBounds(70, 150, 90, 20);
        jPanel2.add(a3);
        a3.setBounds(190, 150, 30, 20);
        jPanel2.add(m4);
        m4.setBounds(70, 176, 90, 20);
        jPanel2.add(a4);
        a4.setBounds(190, 176, 30, 20);

        g2.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Male", "Female" }));
        jPanel2.add(g2);
        g2.setBounds(258, 116, 59, 20);

        p2.setForeground(new java.awt.Color(255, 255, 0));
        p2.setText("2");
        jPanel2.add(p2);
        p2.setBounds(20, 120, 20, 20);

        Fare1.setFont(new java.awt.Font("Bookman Old Style", 0, 18));
        jPanel2.add(Fare1);
        Fare1.setBounds(208, 287, 165, 28);

        p4.setForeground(new java.awt.Color(255, 255, 0));
        p4.setText("4");
        jPanel2.add(p4);
        p4.setBounds(20, 176, 20, 20);

        g3.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Male", "Female" }));
        jPanel2.add(g3);
        g3.setBounds(258, 142, 59, 20);

        p3.setForeground(new java.awt.Color(255, 255, 0));
        p3.setText("3");
        jPanel2.add(p3);
        p3.setBounds(20, 150, 20, 20);

        jLabel22.setFont(new java.awt.Font("Bookman Old Style", 0, 16));
        jLabel22.setForeground(new java.awt.Color(255, 255, 0));
        jLabel22.setText("Bangalore");
        jPanel2.add(jLabel22);
        jLabel22.setBounds(405, 110, 80, 20);

        jLabel19.setFont(new java.awt.Font("Bookman Old Style", 0, 16));
        jLabel19.setForeground(new java.awt.Color(255, 255, 0));
        jLabel19.setText("In Case of bulk booking , either meet the nearest Railway Station or contact :");
        jPanel2.add(jLabel19);
        jLabel19.setBounds(405, 37, 609, 20);

        jLabel27.setFont(new java.awt.Font("Times New Roman", 0, 16));
        jLabel27.setForeground(new java.awt.Color(255, 255, 0));
        jLabel27.setText(" +91-44-2345-6789");
        jPanel2.add(jLabel27);
        jLabel27.setBounds(518, 137, 127, 19);

        jLabel21.setFont(new java.awt.Font("Bookman Old Style", 0, 16));
        jLabel21.setForeground(new java.awt.Color(255, 255, 0));
        jLabel21.setText("Mumbai");
        jPanel2.add(jLabel21);
        jLabel21.setBounds(405, 89, 65, 20);

        jLabel13.setFont(new java.awt.Font("Bookman Old Style", 0, 16));
        jLabel13.setForeground(new java.awt.Color(255, 255, 0));
        jLabel13.setText("Aadhar Card");
        jPanel2.add(jLabel13);
        jLabel13.setBounds(405, 455, 100, 20);

        jLabel20.setFont(new java.awt.Font("Bookman Old Style", 0, 16));
        jLabel20.setForeground(new java.awt.Color(255, 255, 0));
        jLabel20.setText("Delhi ");
        jPanel2.add(jLabel20);
        jLabel20.setBounds(405, 63, 48, 20);

        jLabel2.setForeground(new java.awt.Color(255, 255, 0));
        jLabel2.setText("No. of Passengers");
        jPanel2.add(jLabel2);
        jLabel2.setBounds(20, 11, 200, 14);

        jLabel23.setFont(new java.awt.Font("Bookman Old Style", 0, 16));
        jLabel23.setForeground(new java.awt.Color(255, 255, 0));
        jLabel23.setText("Chennai");
        jPanel2.add(jLabel23);
        jLabel23.setBounds(405, 136, 68, 20);

        jLabel28.setFont(new java.awt.Font("Times New Roman", 0, 16));
        jLabel28.setForeground(new java.awt.Color(255, 255, 0));
        jLabel28.setText(" +91-22-2345-6789");
        jPanel2.add(jLabel28);
        jLabel28.setBounds(518, 90, 127, 19);

        jLabel24.setForeground(new java.awt.Color(255, 255, 0));
        jLabel24.setText("Hyderabad");
        jPanel2.add(jLabel24);
        jLabel24.setBounds(405, 162, 53, 14);

        jLabel33.setForeground(new java.awt.Color(255, 255, 0));
        jLabel33.setText("Fare without taxes per person :");
        jPanel2.add(jLabel33);
        jLabel33.setBounds(10, 296, 190, 14);

        g4.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Male", "Female" }));
        jPanel2.add(g4);
        g4.setBounds(258, 168, 59, 20);
        jPanel2.add(a5);
        a5.setBounds(190, 202, 30, 20);
        jPanel2.add(m5);
        m5.setBounds(70, 202, 90, 20);

        jLabel30.setFont(new java.awt.Font("Times New Roman", 0, 16)); // NOI18N
        jLabel30.setForeground(new java.awt.Color(255, 255, 0));
        jLabel30.setText(" +91-23-2345-6789");
        jPanel2.add(jLabel30);
        jLabel30.setBounds(518, 115, 127, 19);

        p5.setForeground(new java.awt.Color(255, 255, 0));
        p5.setText("5");
        jPanel2.add(p5);
        p5.setBounds(20, 202, 20, 20);

        jLabel31.setFont(new java.awt.Font("Times New Roman", 0, 16));
        jLabel31.setForeground(new java.awt.Color(255, 255, 0));
        jLabel31.setText(" +91-33-2345-6789");
        jPanel2.add(jLabel31);
        jLabel31.setBounds(518, 189, 127, 19);

        g5.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Male", "Female" }));
        jPanel2.add(g5);
        g5.setBounds(258, 194, 59, 20);

        jCheckBox1.setFont(new java.awt.Font("Tahoma", 0, 10));
        jCheckBox1.setText(" I have read the details regarding the Identity proof given in this page");
        jPanel2.add(jCheckBox1);
        jCheckBox1.setBounds(10, 262, 339, 21);

        jLabel32.setForeground(new java.awt.Color(255, 255, 0));
        jLabel32.setText("Or contact our toll free number - 1800-270-2345");
        jPanel2.add(jLabel32);
        jLabel32.setBounds(405, 219, 233, 14);

        jLabel17.setFont(new java.awt.Font("Bookman Old Style", 0, 16));
        jLabel17.setForeground(new java.awt.Color(255, 255, 0));
        jLabel17.setText("1. All the travellers must carry their Identity proof.");
        jPanel2.add(jLabel17);
        jLabel17.setBounds(405, 269, 398, 20);

        jLabel14.setFont(new java.awt.Font("Bookman Old Style", 0, 16));
        jLabel14.setForeground(new java.awt.Color(255, 255, 0));
        jLabel14.setText("4. See to it that the photo on the Identity Proof is clear and could be used for its purpose.");
        jPanel2.add(jLabel14);
        jLabel14.setBounds(405, 481, 705, 20);

        jLabel15.setFont(new java.awt.Font("Bookman Old Style", 0, 16));
        jLabel15.setForeground(new java.awt.Color(255, 255, 0));
        jLabel15.setText("5. Also Carry the credit card using which the payment is made. ");
        jPanel2.add(jLabel15);
        jLabel15.setBounds(405, 507, 504, 20);

        jLabel12.setFont(new java.awt.Font("Bookman Old Style", 0, 16));
        jLabel12.setForeground(new java.awt.Color(255, 255, 0));
        jLabel12.setText("Driving License ");
        jPanel2.add(jLabel12);
        jLabel12.setBounds(405, 429, 127, 20);

        jLabel29.setFont(new java.awt.Font("Times New Roman", 0, 16));
        jLabel29.setForeground(new java.awt.Color(255, 255, 0));
        jLabel29.setText(" +91-11-2345-6789");
        jPanel2.add(jLabel29);
        jLabel29.setBounds(518, 64, 127, 19);
        jPanel2.add(a1);
        a1.setBounds(190, 90, 30, 20);

        jLabel8.setFont(new java.awt.Font("Bookman Old Style", 0, 16)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(255, 255, 0));
        jLabel8.setText("3. The following cards can be used as identity :");
        jPanel2.add(jLabel8);
        jLabel8.setBounds(405, 325, 748, 20);
        jPanel2.add(m1);
        m1.setBounds(70, 90, 90, 20);

        jLabel6.setFont(new java.awt.Font("Bookman Old Style", 0, 16)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(255, 255, 0));
        jLabel6.setText("NOTE :");
        jPanel2.add(jLabel6);
        jLabel6.setBounds(405, 239, 55, 20);

        p1.setForeground(new java.awt.Color(255, 255, 0));
        p1.setText("1");
        jPanel2.add(p1);
        p1.setBounds(20, 90, 20, 20);

        jLabel7.setFont(new java.awt.Font("Bookman Old Style", 0, 16));
        jLabel7.setForeground(new java.awt.Color(255, 255, 0));
        jLabel7.setText("2. Please see to it that the name entered for the Ticket is same as that in the Identity Proof.");
        jPanel2.add(jLabel7);
        jLabel7.setBounds(405, 295, 728, 20);

        jLabel5.setForeground(new java.awt.Color(255, 255, 0));
        jLabel5.setText("Gender");
        jPanel2.add(jLabel5);
        jLabel5.setBounds(258, 65, 60, 14);

        jButton1.setText("CONTINUE");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        jPanel2.add(jButton1);
        jButton1.setBounds(120, 42, 110, 23);

        jLabel18.setFont(new java.awt.Font("Bookman Old Style", 0, 16)); // NOI18N
        jLabel18.setForeground(new java.awt.Color(255, 255, 0));
        jLabel18.setText("A Maximum of 5 members can be booked in each ticket.");
        jPanel2.add(jLabel18);
        jLabel18.setBounds(405, 11, 443, 20);

        jButton2.setText("PAYMENT");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        jPanel2.add(jButton2);
        jButton2.setBounds(120, 232, 110, 23);

        jLabel16.setFont(new java.awt.Font("Bookman Old Style", 0, 16)); // NOI18N
        jLabel16.setForeground(new java.awt.Color(255, 255, 0));
        jLabel16.setText("6. If a traveller is not carrying an identity proof. He/She must pay a fine of Rs.1000. ");
        jPanel2.add(jLabel16);
        jLabel16.setBounds(405, 533, 667, 20);

        jLabel25.setFont(new java.awt.Font("Bookman Old Style", 0, 16));
        jLabel25.setForeground(new java.awt.Color(255, 255, 0));
        jLabel25.setText("Kolkata");
        jPanel2.add(jLabel25);
        jLabel25.setBounds(405, 188, 60, 20);

        jLabel26.setFont(new java.awt.Font("Times New Roman", 0, 16));
        jLabel26.setForeground(new java.awt.Color(255, 255, 0));
        jLabel26.setText(" +91-40-2345-6789");
        jPanel2.add(jLabel26);
        jLabel26.setBounds(518, 163, 127, 19);

        jLabel3.setForeground(new java.awt.Color(255, 255, 0));
        jLabel3.setText("S.No");
        jPanel2.add(jLabel3);
        jLabel3.setBounds(20, 65, 40, 14);

        jLabel9.setFont(new java.awt.Font("Bookman Old Style", 0, 16));
        jLabel9.setForeground(new java.awt.Color(255, 255, 0));
        jLabel9.setText("Passport");
        jPanel2.add(jLabel9);
        jLabel9.setBounds(405, 351, 67, 20);

        jLabel4.setForeground(new java.awt.Color(255, 255, 0));
        jLabel4.setText("Name");
        jPanel2.add(jLabel4);
        jLabel4.setBounds(70, 65, 90, 14);

        jLabel10.setFont(new java.awt.Font("Bookman Old Style", 0, 16));
        jLabel10.setForeground(new java.awt.Color(255, 255, 0));
        jLabel10.setText("Pan Card");
        jPanel2.add(jLabel10);
        jLabel10.setBounds(405, 377, 73, 20);

        c1.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "1", "2", "3", "4", "5" }));
        c1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseExited(java.awt.event.MouseEvent evt) {
                c1MouseExited(evt);
            }
        });
        c1.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                c1ItemStateChanged(evt);
            }
        });
        c1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                c1ActionPerformed(evt);
            }
        });
        c1.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                c1FocusLost(evt);
            }
        });
        c1.addInputMethodListener(new java.awt.event.InputMethodListener() {
            public void caretPositionChanged(java.awt.event.InputMethodEvent evt) {
                c1CaretPositionChanged(evt);
            }
            public void inputMethodTextChanged(java.awt.event.InputMethodEvent evt) {
            }
        });
        c1.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                c1KeyTyped(evt);
            }
        });
        jPanel2.add(c1);
        c1.setBounds(230, 11, 120, 20);
        jPanel2.add(m2);
        m2.setBounds(70, 120, 90, 20);

        jLabel11.setForeground(new java.awt.Color(255, 255, 0));
        jLabel11.setText("Age");
        jPanel2.add(jLabel11);
        jLabel11.setBounds(190, 65, 50, 14);

        jLabel34.setFont(new java.awt.Font("Bookman Old Style", 0, 16));
        jLabel34.setForeground(new java.awt.Color(255, 255, 0));
        jLabel34.setText("Ration Card");
        jPanel2.add(jLabel34);
        jLabel34.setBounds(405, 403, 95, 20);
        jPanel2.add(a2);
        a2.setBounds(190, 120, 30, 20);

        g1.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Male", "Female" }));
        jPanel2.add(g1);
        g1.setBounds(258, 90, 59, 20);

        jLabel35.setForeground(new java.awt.Color(255, 255, 0));
        jPanel2.add(jLabel35);
        jLabel35.setBounds(50, 340, 270, 170);

        jPanel1.add(jPanel2);
        jPanel2.setBounds(120, 90, 1140, 560);

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/project_gomo_updating/bck1.png"))); // NOI18N
        jPanel1.add(jLabel1);
        jLabel1.setBounds(0, 0, 1360, 700);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 1360, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 701, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        int num = Integer.parseInt((String)c1.getSelectedItem());
        if(num>=1) {
            p1.setVisible(true); m1.setVisible(true); a1.setVisible(true); g1.setVisible(true);
        }
        if(num>=2) {
            p2.setVisible(true); m2.setVisible(true); a2.setVisible(true); g2.setVisible(true);
        }
        if(num>=3) {
            p3.setVisible(true); m3.setVisible(true); a3.setVisible(true); g3.setVisible(true);
        }
        if(num>=4) {
            p4.setVisible(true); m4.setVisible(true); a4.setVisible(true); g4.setVisible(true);
        }
        if(num==5) {
            p5.setVisible(true); m5.setVisible(true); a5.setVisible(true); g5.setVisible(true);
        }
        try {
            Class.forName("java.sql.DriverManager");
            Connection con = (Connection)DriverManager.getConnection("jdbc:mysql://localhost:3306/gomo","root","DPS");
            Statement s5 = (Statement) con.createStatement();
            String coach="";
            if(project_gomo_updating.Main.Coach.equals("AC")) {
                coach="AC";
            } else if(project_gomo_updating.Main.Coach.equals("Non-AC")) {
                coach="Non_AC";
            } else if(project_gomo_updating.Main.Coach.equals("First Class")) {
                coach="First_Class";
            }
            String count="SELECT "+coach+" from Fare where Departure='"+project_gomo_updating.Main.dep+"' and Arrival ='"+project_gomo_updating.Main.arr+"'";
            ResultSet r= s5.executeQuery(count);
            if(r.next()) {
                int Fare = r.getInt(1);
                project_gomo_updating.Main.fare = project_gomo_updating.Main.fare + Fare ;
                Fare1.setText(""+Fare);
            }
        } catch(Exception e) {
            JOptionPane.showMessageDialog(this, e.getMessage());
        }
}//GEN-LAST:event_jButton1ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:
        if(jCheckBox1.isSelected()) {
            String uname = project_gomo_updating.Main.username;
            String dep = project_gomo_updating.Main.dep;
            String arr = project_gomo_updating.Main.arr;
            String date = project_gomo_updating.Main.dat;
            String ticket = project_gomo_updating.Main.ticket;
            String add = project_gomo_updating.Main.add;
            String coach = project_gomo_updating.Main.Coach;
            String train = project_gomo_updating.Main.train_name;

            int num = Integer.parseInt((String)c1.getSelectedItem());
            project_gomo_updating.Main.number= num;
            if(num>=1) {
                try {
                    Class.forName("java.sql.DriverManager");
                    Connection con = (Connection) DriverManager.getConnection("jdbc:mysql://localhost:3306/gomo","root","DPS");
                    Statement stmt1 = (Statement) con.createStatement();
                    String query1 = "INSERT INTO booking VALUES('" + uname + "','" + dep + "','" + arr + "','" + date + "','" + ticket + "','" + add + "','" + coach + "','" + m1.getText() +"','" + a1.getText() + "','" +(String)g1.getSelectedItem() + "','" + train + "');";
                    stmt1.executeUpdate(query1);

                } catch (Exception e) {
                    JOptionPane.showMessageDialog(this, e.getMessage());
                }
            }
            if(num>=2) {
                try {
                    Class.forName("java.sql.DriverManager");
                    Connection con = (Connection) DriverManager.getConnection("jdbc:mysql://localhost:3306/gomo","root","DPS");
                    Statement stmt2 = (Statement) con.createStatement();
                    String query2 = "INSERT INTO booking VALUES('" + uname + "','" + dep + "','" + arr + "','" + date + "','" + ticket + "','" + add +"','" + coach + "','" + m2.getText() +"','" + a2.getText() + "','" +(String)g2.getSelectedItem() + "','" + train + "');";
                    stmt2.executeUpdate(query2);

                } catch (Exception e) {
                    JOptionPane.showMessageDialog(this, e.getMessage());
                }
            }
            if(num>=3) {
                try {
                    Class.forName("java.sql.DriverManager");
                    Connection con = (Connection) DriverManager.getConnection("jdbc:mysql://localhost:3306/gomo","root","DPS");
                    Statement stmt3 = (Statement) con.createStatement();
                    String query3 = "INSERT INTO booking VALUES('" + uname + "','" + dep + "','" + arr + "','" + date + "','" + ticket + "','" + add +"','" + coach + "','" + m3.getText() +"','" + a3.getText() + "','" +(String)g3.getSelectedItem() + "','" + train + "');";
                    stmt3.executeUpdate(query3);

                } catch (Exception e) {
                    JOptionPane.showMessageDialog(this, e.getMessage());
                }
            }
            if(num>=4) {
                try {
                    Class.forName("java.sql.DriverManager");
                    Connection con = (Connection) DriverManager.getConnection("jdbc:mysql://localhost:3306/gomo","root","DPS");
                    Statement stmt4 = (Statement) con.createStatement();
                    String query4 = "INSERT INTO booking VALUES('" + uname + "','" + dep + "','" + arr + "','" + date + "','" + ticket + "','" + add + "','" + coach +"','" + m4.getText() +"','" + a4.getText() + "','" +(String)g4.getSelectedItem() +"','" + train +  "');";
                    stmt4.executeUpdate(query4);

                } catch (Exception e) {
                    JOptionPane.showMessageDialog(this, e.getMessage());
                }
            }
            if(num==5) {
                try {
                    Class.forName("java.sql.DriverManager");
                    Connection con = (Connection) DriverManager.getConnection("jdbc:mysql://localhost:3306/gomo","root","DPS");
                    Statement stmt5 = (Statement) con.createStatement();
                    String query5 = "INSERT INTO booking VALUES('" + uname + "','" + dep + "','" + arr + "','" + date + "','" + ticket + "','" + add +"','" + coach + "','" + m5.getText() +"','" + a5.getText() + "','" +(String)g5.getSelectedItem() +"','" + train +  "');";
                    stmt5.executeUpdate(query5);

                } catch (Exception e) {
                    JOptionPane.showMessageDialog(this, e.getMessage());
                }
            }project_gomo_7 b = new project_gomo_7();
            b.setVisible(true);
            this.dispose();
        } else {
            JOptionPane.showMessageDialog(this,"Please check the Identity proof details and mark the box given below." );}
}//GEN-LAST:event_jButton2ActionPerformed

    private void c1MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_c1MouseExited
        // TODO add your handling code here:
}//GEN-LAST:event_c1MouseExited

    private void c1ItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_c1ItemStateChanged

}//GEN-LAST:event_c1ItemStateChanged

    private void c1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_c1ActionPerformed
        // TODO add your handling code here:
}//GEN-LAST:event_c1ActionPerformed

    private void c1FocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_c1FocusLost

}//GEN-LAST:event_c1FocusLost

    private void c1CaretPositionChanged(java.awt.event.InputMethodEvent evt) {//GEN-FIRST:event_c1CaretPositionChanged
        // TODO add your handling code here:
}//GEN-LAST:event_c1CaretPositionChanged

    private void c1KeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_c1KeyTyped
        // TODO add your handling code here:
}//GEN-LAST:event_c1KeyTyped

    /**
    * @param args the command line arguments
    */
    public static void main(String args[]) {
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new project_gomo_6().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField Fare1;
    private javax.swing.JTextField a1;
    private javax.swing.JTextField a2;
    private javax.swing.JTextField a3;
    private javax.swing.JTextField a4;
    private javax.swing.JTextField a5;
    private javax.swing.JComboBox c1;
    private javax.swing.JComboBox g1;
    private javax.swing.JComboBox g2;
    private javax.swing.JComboBox g3;
    private javax.swing.JComboBox g4;
    private javax.swing.JComboBox g5;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JCheckBox jCheckBox1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel22;
    private javax.swing.JLabel jLabel23;
    private javax.swing.JLabel jLabel24;
    private javax.swing.JLabel jLabel25;
    private javax.swing.JLabel jLabel26;
    private javax.swing.JLabel jLabel27;
    private javax.swing.JLabel jLabel28;
    private javax.swing.JLabel jLabel29;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel30;
    private javax.swing.JLabel jLabel31;
    private javax.swing.JLabel jLabel32;
    private javax.swing.JLabel jLabel33;
    private javax.swing.JLabel jLabel34;
    private javax.swing.JLabel jLabel35;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JTextField m1;
    private javax.swing.JTextField m2;
    private javax.swing.JTextField m3;
    private javax.swing.JTextField m4;
    private javax.swing.JTextField m5;
    private javax.swing.JLabel p1;
    private javax.swing.JLabel p2;
    private javax.swing.JLabel p3;
    private javax.swing.JLabel p4;
    private javax.swing.JLabel p5;
    // End of variables declaration//GEN-END:variables

}
