package project_gomo_updating;

/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * project_gomo_2.java
 *
 * Created on Jul 26, 2013, 10:07:22 AM
 */

/**
 *
 * @author Student
 */
import javax.swing.Timer;
import java.awt.event.*;

public class project_gomo_2 extends javax.swing.JFrame {

    String abcde;
    Timer t;
    /** Creates new form project_gomo_2 */

   

   public project_gomo_2(String abcd) {
       abcde=abcd;
       initComponents();
       l1.setVisible(false);
       l2.setVisible(false);
       l3.setVisible(false);
       l4.setVisible(false);
        t = new Timer(1000,new ActionListener()
        {
            int s=0 ;
         public void actionPerformed(ActionEvent e)
         {
          s=s+1;
          if(s/8!=1)
          {
              if(s%8==1)
              {
                  l1.setVisible(true);
                if(abcde.equals("1"))
                {
                jLabel2.setText("Please wait as we load up your account");
                }
                else if(abcde.equals("2"))
                {
                jLabel2.setText("Loading trains");
                }
              } 
              else if (s % 8 == 3)
              {
                  l2.setVisible(true);
                  if(abcde.equals("1"))
                {
                jLabel2.setText("Please wait as we load up your account");
                }
                else if(abcde.equals("2"))
                {
                jLabel2.setText("Loading trains");
                }
              }
              else if(s%8==5)
              {
                  l3.setVisible(true);
                  if(abcde.equals("1"))
                {
                jLabel2.setText("Please wait as we load up your account");
                }
                else if(abcde.equals("2"))
                {
                jLabel2.setText("Loading trains");
                }
              }
             else if(s%8==7)
             {
                 l1.setVisible(false);l2.setVisible(false);l3.setVisible(false);l4.setVisible(true);
                 if(abcde.equals("1"))
                {
                jLabel2.setText("Please wait as we load up your account");
                }
                else if(abcde.equals("2"))
                {
                jLabel2.setText("Loading trains");
                }
             }

          }
          else
          {
           
           if(abcde.equals("1"))
           {
              jLabel2.setText("Please wait as we load up your account");
               project_gomo_3 sum = new project_gomo_3();
               sum.setVisible(true);
               project_gomo_2.this.dispose();
           }
           else if(abcde.equals("2"))
           {
               jLabel2.setText("Loading trains");
               project_gomo_5_2 sum = new project_gomo_5_2();
               sum.setVisible(true);
               project_gomo_2.this.dispose();
           }t.stop();
         }
         }
        });t.start();
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel4 = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        l3 = new javax.swing.JLabel();
        l1 = new javax.swing.JLabel();
        l2 = new javax.swing.JLabel();
        l4 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setMinimumSize(new java.awt.Dimension(1365, 710));
        getContentPane().setLayout(null);
        getContentPane().add(jLabel4);
        jLabel4.setBounds(10, 7, 0, 0);

        jPanel1.setLayout(null);

        jLabel2.setFont(new java.awt.Font("Tahoma", 0, 14));
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jPanel1.add(jLabel2);
        jLabel2.setBounds(20, 20, 750, 30);

        l3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/project_gomo_updating/10-Most-Beautiful-and-Incredible-Rail-Journeys-of-India.jpg"))); // NOI18N
        jPanel1.add(l3);
        l3.setBounds(290, 300, 390, 328);

        l1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/project_gomo_updating/images.jpg"))); // NOI18N
        jPanel1.add(l1);
        l1.setBounds(80, 80, 280, 180);

        l2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/project_gomo_updating/images (2).jpg"))); // NOI18N
        jPanel1.add(l2);
        l2.setBounds(800, 150, 260, 194);

        l4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/project_gomo_updating/train1.jpg"))); // NOI18N
        jPanel1.add(l4);
        l4.setBounds(180, 70, 1000, 570);

        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/project_gomo_updating/35.gif"))); // NOI18N
        jPanel1.add(jLabel3);
        jLabel3.setBounds(30, 620, 60, 50);

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/project_gomo_updating/Untitled.png"))); // NOI18N
        jPanel1.add(jLabel1);
        jLabel1.setBounds(0, 0, 1360, 700);

        getContentPane().add(jPanel1);
        jPanel1.setBounds(0, 0, 1360, 700);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
    * @param args the command line arguments
    */
    public static void main(String args[]) {
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JLabel l1;
    private javax.swing.JLabel l2;
    private javax.swing.JLabel l3;
    private javax.swing.JLabel l4;
    // End of variables declaration//GEN-END:variables

}
