/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * project_gomo_8.java
 *
 * Created on 10 Nov, 2013, 6:38:34 PM
 */

package project_gomo_updating;

/**
 *
 * @author Nikhil
 */
import com.mysql.jdbc.Statement;
import com.mysql.jdbc.Connection;
import java.sql.DriverManager;
import java.sql.ResultSet;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

public class project_gomo_8 extends javax.swing.JFrame {

    /** Creates new form project_gomo_8 */
    public project_gomo_8() {
        initComponents();
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        jScrollPane3 = new javax.swing.JScrollPane();
        jTable2 = new javax.swing.JTable();
        l3 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        l5 = new javax.swing.JLabel();
        l6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        l7 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        l4 = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        jTable3 = new javax.swing.JTable();
        jButton1 = new javax.swing.JButton();
        jLabel5 = new javax.swing.JLabel();
        l1 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jLabel2 = new javax.swing.JLabel();
        l2 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jButton2 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        jLabel9 = new javax.swing.JLabel();
        jLabel20 = new javax.swing.JLabel();
        l8 = new javax.swing.JLabel();
        jLabel35 = new javax.swing.JLabel();
        jLabel31 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setMinimumSize(new java.awt.Dimension(1365, 710));
        getContentPane().setLayout(null);

        jPanel1.setLayout(null);

        jPanel2.setLayout(null);

        jTable2.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Arrival Time"
            }
        ));
        jScrollPane3.setViewportView(jTable2);

        jPanel2.add(jScrollPane3);
        jScrollPane3.setBounds(429, 133, 446, 43);

        l3.setFont(new java.awt.Font("Bookman Old Style", 0, 18));
        jPanel2.add(l3);
        l3.setBounds(115, 100, 296, 27);

        jLabel3.setFont(new java.awt.Font("Bookman Old Style", 0, 15));
        jLabel3.setText("Date :");
        jPanel2.add(jLabel3);
        jLabel3.setBounds(10, 100, 67, 27);

        l5.setFont(new java.awt.Font("Bookman Old Style", 0, 18));
        jPanel2.add(l5);
        l5.setBounds(560, 100, 296, 27);

        l6.setFont(new java.awt.Font("Bookman Old Style", 0, 18));
        jPanel2.add(l6);
        l6.setBounds(579, 67, 296, 27);

        jLabel7.setFont(new java.awt.Font("Bookman Old Style", 0, 15));
        jLabel7.setText("Address :");
        jPanel2.add(jLabel7);
        jLabel7.setBounds(10, 295, 70, 19);

        l7.setFont(new java.awt.Font("Bookman Old Style", 0, 15));
        jPanel2.add(l7);
        l7.setBounds(90, 300, 790, 17);

        jLabel4.setFont(new java.awt.Font("Bookman Old Style", 0, 15));
        jLabel4.setText("Train Name :");
        jPanel2.add(jLabel4);
        jLabel4.setBounds(429, 34, 98, 27);

        l4.setFont(new java.awt.Font("Bookman Old Style", 0, 18));
        jPanel2.add(l4);
        l4.setBounds(579, 34, 296, 27);

        jTable3.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Name", "Age", "Gender"
            }
        ));
        jScrollPane2.setViewportView(jTable3);

        jPanel2.add(jScrollPane2);
        jScrollPane2.setBounds(10, 180, 865, 107);

        jButton1.setFont(new java.awt.Font("Tahoma", 0, 14));
        jButton1.setText("Click here to check the final details of the ticket");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        jPanel2.add(jButton1);
        jButton1.setBounds(10, 3, 865, 25);

        jLabel5.setFont(new java.awt.Font("Bookman Old Style", 0, 15));
        jLabel5.setText("Coach :");
        jPanel2.add(jLabel5);
        jLabel5.setBounds(429, 67, 67, 27);

        l1.setFont(new java.awt.Font("Bookman Old Style", 0, 18));
        jPanel2.add(l1);
        l1.setBounds(115, 34, 296, 27);

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Departure Time"
            }
        ));
        jScrollPane1.setViewportView(jTable1);

        jPanel2.add(jScrollPane1);
        jScrollPane1.setBounds(10, 133, 401, 43);

        jLabel2.setFont(new java.awt.Font("Bookman Old Style", 0, 15));
        jLabel2.setText("Departure :");
        jPanel2.add(jLabel2);
        jLabel2.setBounds(10, 34, 87, 27);

        l2.setFont(new java.awt.Font("Bookman Old Style", 0, 18));
        jPanel2.add(l2);
        l2.setBounds(115, 67, 296, 27);

        jLabel6.setFont(new java.awt.Font("Bookman Old Style", 0, 15));
        jLabel6.setText("Arrival :");
        jPanel2.add(jLabel6);
        jLabel6.setBounds(10, 67, 87, 27);

        jLabel8.setFont(new java.awt.Font("Bookman Old Style", 0, 15));
        jLabel8.setText("Form Of Ticket :");
        jPanel2.add(jLabel8);
        jLabel8.setBounds(429, 100, 122, 27);

        jLabel11.setText("TRAVELLERS MUST REPORT ABOUT HALF AN HOUR BEFORE THE DEPARTURE TIME FOR THE SECURITY CHECK AND FOR SEAT ALLOTMENT");
        jPanel2.add(jLabel11);
        jLabel11.setBounds(20, 330, 850, 14);

        jButton2.setText("SIGN OUT");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        jPanel2.add(jButton2);
        jButton2.setBounds(0, 400, 150, 23);

        jButton3.setText("GIVE FEEDBACKS");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });
        jPanel2.add(jButton3);
        jButton3.setBounds(150, 400, 150, 23);

        jPanel1.add(jPanel2);
        jPanel2.setBounds(20, 20, 890, 420);

        jLabel9.setIcon(new javax.swing.ImageIcon(getClass().getResource("/project_gomo_updating/images (5).jpg"))); // NOI18N
        jPanel1.add(jLabel9);
        jLabel9.setBounds(460, 510, 270, 150);

        jLabel20.setIcon(new javax.swing.ImageIcon(getClass().getResource("/project_gomo_updating/delhi.jpg"))); // NOI18N
        jPanel1.add(jLabel20);
        jLabel20.setBounds(940, 10, 320, 160);

        l8.setIcon(new javax.swing.ImageIcon(getClass().getResource("/project_gomo_updating/kolkata.jpg"))); // NOI18N
        jPanel1.add(l8);
        l8.setBounds(1010, 210, 340, 150);

        jLabel35.setIcon(new javax.swing.ImageIcon(getClass().getResource("/project_gomo_updating/chennai.jpg"))); // NOI18N
        jPanel1.add(jLabel35);
        jLabel35.setBounds(770, 490, 270, 190);

        jLabel31.setIcon(new javax.swing.ImageIcon(getClass().getResource("/project_gomo_updating/Mumbai.jpg"))); // NOI18N
        jPanel1.add(jLabel31);
        jLabel31.setBounds(1090, 450, 260, 160);

        jLabel10.setIcon(new javax.swing.ImageIcon(getClass().getResource("/project_gomo_updating/10-Most-Beautiful-and-Incredible-Rail-Journeys-of-India.jpg"))); // NOI18N
        jPanel1.add(jLabel10);
        jLabel10.setBounds(30, 450, 390, 230);

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/project_gomo_updating/Backgrounds-modern-wallpapers-hd-modern-wallpaper-06.jpg"))); // NOI18N
        jPanel1.add(jLabel1);
        jLabel1.setBounds(0, 0, 1360, 700);

        getContentPane().add(jPanel1);
        jPanel1.setBounds(0, 0, 1360, 700);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        l1.setText(project_gomo_updating.Main.dep);
        l2.setText(project_gomo_updating.Main.arr);
        l3.setText(project_gomo_updating.Main.dat);
        l4.setText(project_gomo_updating.Main.train_name);
        l6.setText(project_gomo_updating.Main.Coach);
        l5.setText(project_gomo_updating.Main.ticket);
        if(project_gomo_updating.Main.ticket.equals("E-Ticket")) {
            l7.setText("You have chosen E-Ticket as your form of ticket.");
        } else if(project_gomo_updating.Main.ticket.equals("I-Ticket")) {
            l7.setText(project_gomo_updating.Main.add);
        }
        String train="";
        if(project_gomo_updating.Main.train_name.equals("Express One")) {
            train="Express_One";
        } else if(project_gomo_updating.Main.train_name.equals("Express Two")) {
            train="Express_Two";
        } else if(project_gomo_updating.Main.train_name.equals("Express Three")) {
            train="Express_Three";
        } else if(project_gomo_updating.Main.train_name.equals("Express Four")) {
            train="Express_Four";
        }
        if(project_gomo_updating.Main.dep.equals("Delhi")) {
            DefaultTableModel model = (DefaultTableModel) jTable1.getModel();
            try {
                Class.forName("java.sql.DriverManager");
                Connection con = (Connection)DriverManager.getConnection("jdbc:mysql://localhost:3306/gomo","root","DPS");
                Statement s = (Statement) con.createStatement();
                String query = "SELECT Departure FROM "+train+" where Place='Delhi1';";
                ResultSet r= s.executeQuery(query);
                while(r.next()) {
                    String time_dep = r.getString(1);
                    model.addRow(new Object[]{time_dep});
                }
            } catch(Exception e) {
                JOptionPane.showMessageDialog(this, e.getMessage());
            }
        } else {
            DefaultTableModel model = (DefaultTableModel) jTable1.getModel();
            try {
                Class.forName("java.sql.DriverManager");
                Connection con = (Connection)DriverManager.getConnection("jdbc:mysql://localhost:3306/gomo","root","DPS");
                Statement s = (Statement) con.createStatement();
                String query = "SELECT Departure FROM "+train+" where Place='"+project_gomo_updating.Main.dep+"';";
                ResultSet r= s.executeQuery(query);
                while(r.next()) {
                    String time_dep = r.getString(1);
                    model.addRow(new Object[]{time_dep});

                }
            } catch(Exception e) {
                JOptionPane.showMessageDialog(this, e.getMessage());
            }
        }
        if(project_gomo_updating.Main.arr.equals("Delhi")) {
            DefaultTableModel model = (DefaultTableModel) jTable2.getModel();
            try {
                Class.forName("java.sql.DriverManager");
                Connection con = (Connection)DriverManager.getConnection("jdbc:mysql://localhost:3306/gomo","root","DPS");
                Statement s = (Statement) con.createStatement();
                String query = "SELECT Arrival FROM "+train+" where Place='Delhi2';";
                ResultSet r= s.executeQuery(query);
                while(r.next()) {
                    String time_arr = r.getString(1);
                    model.addRow(new Object[]{time_arr});
                }
            } catch(Exception e) {
                JOptionPane.showMessageDialog(this, e.getMessage());
            }
        } else {
            DefaultTableModel model = (DefaultTableModel) jTable2.getModel();
            try {
                Class.forName("java.sql.DriverManager");
                Connection con = (Connection)DriverManager.getConnection("jdbc:mysql://localhost:3306/gomo","root","DPS");
                Statement s = (Statement) con.createStatement();
                String query = "SELECT Arrival FROM "+train+" where Place='"+project_gomo_updating.Main.arr+"';";
                ResultSet r= s.executeQuery(query);
                while(r.next()) {
                    String time_arr = r.getString(1);
                    model.addRow(new Object[]{time_arr});
                }
            } catch(Exception e) {
                JOptionPane.showMessageDialog(this, e.getMessage());
            }
        }
        DefaultTableModel model = (DefaultTableModel) jTable3.getModel();
        try {
            Class.forName("java.sql.DriverManager");
            Connection con = (Connection)DriverManager.getConnection("jdbc:mysql://localhost:3306/gomo","root","DPS");
            Statement s = (Statement) con.createStatement();
            String query = "SELECT Name, Age , Gender FROM booking where username='"+project_gomo_updating.Main.username+"' and Departure='"+project_gomo_updating.Main.dep+"' and Arrival='"+project_gomo_updating.Main.arr+"' and Date='"+project_gomo_updating.Main.dat+"' and Coach='"+project_gomo_updating.Main.Coach+"';";
            ResultSet r= s.executeQuery(query);
            while(r.next()) {
                String Name = r.getString(1);
                String age = r.getString(2);
                String gender = r.getString(3);
                model.addRow(new Object[]{Name,age,gender});

            }
        } catch(Exception e) {
            JOptionPane.showMessageDialog(this, e.getMessage());
        }
}//GEN-LAST:event_jButton1ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        gomo_openingpage a= new gomo_openingpage();
        a.setVisible(true);
        this.dispose();
        JOptionPane.showMessageDialog(null,"You are successfully logged out !!");
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        // TODO add your handling code here:
        gomo_feedback b= new gomo_feedback();
        b.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_jButton3ActionPerformed

    /**
    * @param args the command line arguments
    */
    public static void main(String args[]) {
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new project_gomo_8().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel31;
    private javax.swing.JLabel jLabel35;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JTable jTable1;
    private javax.swing.JTable jTable2;
    private javax.swing.JTable jTable3;
    private javax.swing.JLabel l1;
    private javax.swing.JLabel l2;
    private javax.swing.JLabel l3;
    private javax.swing.JLabel l4;
    private javax.swing.JLabel l5;
    private javax.swing.JLabel l6;
    private javax.swing.JLabel l7;
    private javax.swing.JLabel l8;
    // End of variables declaration//GEN-END:variables

}
