/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * project_gomo_7.java
 *
 * Created on Nov 8, 2013, 10:14:15 AM
 */

package project_gomo_updating;

import project_gomo_updating.project_gomo_2;
import com.mysql.jdbc.Statement;
import com.mysql.jdbc.Connection;
import java.sql.DriverManager;
import java.sql.ResultSet;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
public class project_gomo_7 extends javax.swing.JFrame {

    /** Creates new form project_gomo_7 */
    public project_gomo_7() {
        initComponents();
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        c1 = new javax.swing.JComboBox();
        t7 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        Fare1 = new javax.swing.JLabel();
        jTextField1 = new javax.swing.JLabel();
        t9 = new javax.swing.JTextField();
        jLabel9 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jLabel11 = new javax.swing.JLabel();
        t8 = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        jComboBox1 = new javax.swing.JComboBox();
        jLabel5 = new javax.swing.JLabel();
        jButton5 = new javax.swing.JButton();
        p2 = new javax.swing.JPasswordField();
        jLabel6 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        t10 = new javax.swing.JTextField();
        t11 = new javax.swing.JTextField();
        jButton1 = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setMinimumSize(new java.awt.Dimension(1365, 701));
        getContentPane().setLayout(null);

        jPanel1.setLayout(null);

        c1.setFont(new java.awt.Font("Bookman Old Style", 0, 18));
        c1.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Select payment gateway", "Mastercard", "Visa", "American Express" }));
        c1.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                c1FocusLost(evt);
            }
        });
        jPanel1.add(c1);
        c1.setBounds(40, 250, 404, 28);

        t7.setFont(new java.awt.Font("Tahoma", 0, 14));
        t7.setForeground(new java.awt.Color(255, 255, 255));
        jPanel1.add(t7);
        t7.setBounds(170, 290, 280, 30);

        jLabel7.setFont(new java.awt.Font("Tahoma", 0, 14));
        jLabel7.setForeground(new java.awt.Color(255, 255, 255));
        jLabel7.setText("FINAL FARE :");
        jPanel1.add(jLabel7);
        jLabel7.setBounds(40, 290, 130, 30);

        Fare1.setFont(new java.awt.Font("Tahoma", 0, 14));
        Fare1.setForeground(new java.awt.Color(255, 255, 255));
        jPanel1.add(Fare1);
        Fare1.setBounds(270, 150, 200, 30);

        jTextField1.setFont(new java.awt.Font("Tahoma", 0, 14));
        jTextField1.setForeground(new java.awt.Color(255, 255, 255));
        jPanel1.add(jTextField1);
        jTextField1.setBounds(270, 180, 200, 30);

        t9.setFont(new java.awt.Font("Bookman Old Style", 0, 18));
        t9.addCaretListener(new javax.swing.event.CaretListener() {
            public void caretUpdate(javax.swing.event.CaretEvent evt) {
                t9CaretUpdate(evt);
            }
        });
        t9.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                t9KeyTyped(evt);
            }
        });
        jPanel1.add(t9);
        t9.setBounds(137, 361, 88, 27);

        jLabel9.setFont(new java.awt.Font("Bookman Old Style", 0, 18));
        jLabel9.setForeground(new java.awt.Color(255, 255, 255));
        jLabel9.setText("Credit Card No.");
        jPanel1.add(jLabel9);
        jLabel9.setBounds(36, 333, 137, 22);

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Departure", "Arrival", "AC", "Non-AC", "First Class"
            }
        ));
        jScrollPane1.setViewportView(jTable1);

        jPanel1.add(jScrollPane1);
        jScrollPane1.setBounds(36, 104, 404, 42);

        jLabel11.setFont(new java.awt.Font("Bookman Old Style", 0, 18));
        jLabel11.setForeground(new java.awt.Color(255, 255, 255));
        jLabel11.setText("CVV");
        jPanel1.add(jLabel11);
        jLabel11.setBounds(36, 405, 39, 22);

        t8.setFont(new java.awt.Font("Bookman Old Style", 0, 18));
        t8.addCaretListener(new javax.swing.event.CaretListener() {
            public void caretUpdate(javax.swing.event.CaretEvent evt) {
                t8CaretUpdate(evt);
            }
        });
        t8.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                t8FocusLost(evt);
            }
        });
        t8.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                t8KeyTyped(evt);
            }
        });
        jPanel1.add(t8);
        t8.setBounds(36, 361, 95, 27);

        jLabel4.setFont(new java.awt.Font("Bookman Old Style", 0, 18));
        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setText("Fare with other charges :");
        jPanel1.add(jLabel4);
        jLabel4.setBounds(36, 181, 224, 22);

        jComboBox1.setFont(new java.awt.Font("Bookman Old Style", 0, 18));
        jComboBox1.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Bank Name", "Axis Bank", "Citi Bank", "ICICI Bank", "SBI" }));
        jPanel1.add(jComboBox1);
        jComboBox1.setBounds(153, 209, 287, 28);

        jLabel5.setFont(new java.awt.Font("Bookman Old Style", 0, 18));
        jLabel5.setForeground(new java.awt.Color(255, 255, 255));
        jLabel5.setText("Bank Name :");
        jPanel1.add(jLabel5);
        jLabel5.setBounds(36, 212, 113, 22);

        jButton5.setFont(new java.awt.Font("Bookman Old Style", 0, 18));
        jButton5.setText("Next");
        jButton5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton5ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton5);
        jButton5.setBounds(36, 438, 146, 31);

        p2.setFont(new java.awt.Font("Bookman Old Style", 0, 18));
        p2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                p2ActionPerformed(evt);
            }
        });
        p2.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                p2KeyTyped(evt);
            }
        });
        jPanel1.add(p2);
        p2.setBounds(137, 399, 88, 28);

        jLabel6.setFont(new java.awt.Font("Bookman Old Style", 0, 18));
        jLabel6.setForeground(new java.awt.Color(255, 255, 255));
        jLabel6.setText("Total Fare without Taxes:");
        jPanel1.add(jLabel6);
        jLabel6.setBounds(36, 153, 227, 22);

        jLabel2.setFont(new java.awt.Font("Bookman Old Style", 0, 18));
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("Service Charges   :         10 %");
        jPanel1.add(jLabel2);
        jLabel2.setBounds(36, 11, 267, 22);

        t10.setFont(new java.awt.Font("Bookman Old Style", 0, 18));
        t10.addCaretListener(new javax.swing.event.CaretListener() {
            public void caretUpdate(javax.swing.event.CaretEvent evt) {
                t10CaretUpdate(evt);
            }
        });
        t10.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                t10KeyTyped(evt);
            }
        });
        jPanel1.add(t10);
        t10.setBounds(231, 361, 101, 27);

        t11.setFont(new java.awt.Font("Bookman Old Style", 0, 18));
        t11.addCaretListener(new javax.swing.event.CaretListener() {
            public void caretUpdate(javax.swing.event.CaretEvent evt) {
                t11CaretUpdate(evt);
            }
        });
        t11.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                t11KeyTyped(evt);
            }
        });
        jPanel1.add(t11);
        t11.setBounds(338, 361, 102, 27);

        jButton1.setFont(new java.awt.Font("Bookman Old Style", 0, 18));
        jButton1.setText("Click here to Check the total fares");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton1);
        jButton1.setBounds(36, 67, 404, 31);

        jLabel3.setFont(new java.awt.Font("Bookman Old Style", 0, 18));
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("TAX                    :         10%");
        jPanel1.add(jLabel3);
        jLabel3.setBounds(40, 40, 280, 20);

        jLabel8.setIcon(new javax.swing.ImageIcon(getClass().getResource("/project_gomo_updating/luxury-train-travel.jpg"))); // NOI18N
        jPanel1.add(jLabel8);
        jLabel8.setBounds(480, 70, 720, 409);

        jLabel10.setFont(new java.awt.Font("Monotype Corsiva", 1, 24));
        jLabel10.setForeground(new java.awt.Color(255, 255, 0));
        jLabel10.setText("Our First Class Coach...");
        jPanel1.add(jLabel10);
        jLabel10.setBounds(230, 650, 260, 28);

        jLabel12.setFont(new java.awt.Font("Monotype Corsiva", 0, 18)); // NOI18N
        jLabel12.setText("Our First Class Coach ....");
        jPanel1.add(jLabel12);
        jLabel12.setBounds(480, 500, 190, 30);

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/project_gomo_updating/fnpfnf.png"))); // NOI18N
        jPanel1.add(jLabel1);
        jLabel1.setBounds(0, 0, 1360, 700);

        getContentPane().add(jPanel1);
        jPanel1.setBounds(0, 0, 1220, 560);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void c1FocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_c1FocusLost
        // TODO add your handling code here:
        {
            if (c1.getSelectedIndex() == 1) {
                Double x = 0.9 * Double.parseDouble(jTextField1.getText());long a = Math.round(x);t7.setText(""+a);
            } else if(c1.getSelectedIndex()==2) {
                Double x = 0.92 * Double.parseDouble(jTextField1.getText());long a = Math.round(x);t7.setText(""+a);
            } else if(c1.getSelectedIndex()==3) {
                Double x = 0.87 * Double.parseDouble(jTextField1.getText());long a = Math.round(x);t7.setText(""+a);
            }
        }
}//GEN-LAST:event_c1FocusLost

    private void t9CaretUpdate(javax.swing.event.CaretEvent evt) {//GEN-FIRST:event_t9CaretUpdate
        // TODO add your handling code here:
}//GEN-LAST:event_t9CaretUpdate

    private void t9KeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_t9KeyTyped
        // TODO add your handling code here:
        String x = t9.getText();
        int l = x.length();
        if(l>=4) {
            x = x.substring(0,3);
            t9.setText(x);
        }
}//GEN-LAST:event_t9KeyTyped

    private void t8CaretUpdate(javax.swing.event.CaretEvent evt) {//GEN-FIRST:event_t8CaretUpdate
        // TODO add your handling code here:
}//GEN-LAST:event_t8CaretUpdate

    private void t8FocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_t8FocusLost
        // TODO add your handling code here:
}//GEN-LAST:event_t8FocusLost

    private void t8KeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_t8KeyTyped
        // TODO add your handling code here:
        String x = t8.getText();
        int l = x.length();
        if(l>=4) {
            x = x.substring(0,3);
            t8.setText(x);
        }
}//GEN-LAST:event_t8KeyTyped

    private void jButton5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton5ActionPerformed
        // TODO add your handling code here:
        project_gomo_8 b = new project_gomo_8();
        b.setVisible(true);
        this.dispose();
}//GEN-LAST:event_jButton5ActionPerformed

    private void p2KeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_p2KeyTyped
        // TODO add your handling code here:
        String x = new String (p2.getPassword());
        int l = x.length();
        if(l>=3)
        {
            x = x.substring(0,2);
            p2.setText(x);
        }
}//GEN-LAST:event_p2KeyTyped

    private void t10CaretUpdate(javax.swing.event.CaretEvent evt) {//GEN-FIRST:event_t10CaretUpdate
        // TODO add your handling code here:
}//GEN-LAST:event_t10CaretUpdate

    private void t10KeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_t10KeyTyped
        // TODO add your handling code here:
        String x = t10.getText();
        int l = x.length();
        if(l>=4) {
            x = x.substring(0,3);
            t10.setText(x);
        }
}//GEN-LAST:event_t10KeyTyped

    private void t11CaretUpdate(javax.swing.event.CaretEvent evt) {//GEN-FIRST:event_t11CaretUpdate
        // TODO add your handling code here:
}//GEN-LAST:event_t11CaretUpdate

    private void t11KeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_t11KeyTyped
        String x = t11.getText();
        int l = x.length();
        if(l>=4) {
            x = x.substring(0,3);
            t11.setText(x);
        }
}//GEN-LAST:event_t11KeyTyped

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        String coach="";
        if(project_gomo_updating.Main.Coach.equals("AC")) {
            coach="AC";
        } else if(project_gomo_updating.Main.Coach.equals("Non-AC")) {
            coach="Non_AC";
        } else if(project_gomo_updating.Main.Coach.equals("First Class")) {
            coach="First_Class";
        }
        DefaultTableModel model = (DefaultTableModel) jTable1.getModel();
        try {
            Class.forName("java.sql.DriverManager");
            Connection con = (Connection)DriverManager.getConnection("jdbc:mysql://localhost:3306/gomo","root","DPS");
            Statement s5 = (Statement) con.createStatement();
            String count="SELECT * from Fare where Departure='"+project_gomo_updating.Main.dep+"' and Arrival ='"+project_gomo_updating.Main.arr+"'";
            ResultSet r= s5.executeQuery(count);
            if(r.next()) {
                String Dept = r.getString(1);
                String Arrival = r.getString(2);
                int AC = r.getInt(3);
                int Non_AC = r.getInt(4);
                int First_Class = r.getInt(5);
                model.addRow(new Object[]{Dept,Arrival,AC,Non_AC,First_Class});
            }
        } catch(Exception e) {
            JOptionPane.showMessageDialog(this, e.getMessage());
        }
        int numdep=JOptionPane.showConfirmDialog(this,"Is your place of Departure "+project_gomo_updating.Main.dep+" ?","Confirm Departure",JOptionPane.YES_NO_OPTION);
        if(numdep==0) {
            int numarr=JOptionPane.showConfirmDialog(this,"Is your place of Arrival "+project_gomo_updating.Main.arr+" ?","Confirm",JOptionPane.YES_NO_OPTION);
            if(numarr==0) {
                int numdate=JOptionPane.showConfirmDialog(this,"Are you travelling on "+project_gomo_updating.Main.dat+" ?","Confirm",JOptionPane.YES_NO_OPTION);
                if(numdate==0) {
                    Float total_fare = (float)project_gomo_updating.Main.number*project_gomo_updating.Main.fare;
                    Fare1.setText(" "+total_fare+"0");
                    Double x = 0.12*total_fare;
                    long a = Math.round(x);
                    jTextField1.setText(" "+a*10+".00");
                } else{JOptionPane.showMessageDialog(this, "You have made a mistake while booking.Please start back the procedure.");
                try {
                    Class.forName("java.sql.DriverManager");
                    Connection con = (Connection)DriverManager.getConnection("jdbc:mysql://localhost:3306/gomo","root","DPS");
                    Statement s5 = (Statement) con.createStatement();
                    String count="Delete from booking where username="+project_gomo_updating.Main.username+" from booking where Date='"+project_gomo_updating.Main.dat+"' and Arrival ='"+project_gomo_updating.Main.arr+"' and Departure ='"+project_gomo_updating.Main.arr+"'";
                    s5.executeUpdate(count);
                } catch(Exception e) {
                    JOptionPane.showMessageDialog(this, e.getMessage());
                }  }
            } else{JOptionPane.showMessageDialog(this, "You have made a mistake while booking.Please start back the procedure.");
            try {
                Class.forName("java.sql.DriverManager");
                Connection con = (Connection)DriverManager.getConnection("jdbc:mysql://localhost:3306/gomo","root","DPS");
                Statement s5 = (Statement) con.createStatement();
                String count="Delete from booking where username="+project_gomo_updating.Main.username+" from booking where Date='"+project_gomo_updating.Main.dat+"' and Arrival ='"+project_gomo_updating.Main.arr+"' and Departure ='"+project_gomo_updating.Main.arr+"'";
                s5.executeUpdate(count);
            } catch(Exception e) {
                JOptionPane.showMessageDialog(this, e.getMessage());
            }}
        } else {
            JOptionPane.showMessageDialog(this, "You have made a mistake while booking.Please start back the procedure.");
            try {
                Class.forName("java.sql.DriverManager");
                Connection con = (Connection)DriverManager.getConnection("jdbc:mysql://localhost:3306/gomo","root","DPS");
                Statement s5 = (Statement) con.createStatement();
                String count="Delete from booking where username="+project_gomo_updating.Main.username+" from booking where Date='"+project_gomo_updating.Main.dat+"' and Arrival ='"+project_gomo_updating.Main.arr+"' and Departure ='"+project_gomo_updating.Main.arr+"'";
                s5.executeUpdate(count);
            } catch(Exception e) {
                JOptionPane.showMessageDialog(this, e.getMessage());
            }}
}//GEN-LAST:event_jButton1ActionPerformed

    private void p2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_p2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_p2ActionPerformed

    /**
    * @param args the command line arguments
    */
    public static void main(String args[]) {
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new project_gomo_7().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel Fare1;
    private javax.swing.JComboBox c1;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton5;
    private javax.swing.JComboBox jComboBox1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTable1;
    private javax.swing.JLabel jTextField1;
    private javax.swing.JPasswordField p2;
    private javax.swing.JTextField t10;
    private javax.swing.JTextField t11;
    private javax.swing.JLabel t7;
    private javax.swing.JTextField t8;
    private javax.swing.JTextField t9;
    // End of variables declaration//GEN-END:variables

}
